### ISSUE TITLE
Exam timing is in GMT+0

### ISSUE THREAD

**Issue by chrisjwelly** [seanlowjk/nusexamscountdown#1]
### Issue
The time of the module exams is in GMT+0. This subsequently affects the countdown as well. I think it would make more sense to make it GMT+8.

### Screenshot
Screenshot taken on 6 July 2019. The query is requested at 10:57. Ignoring the days and looking at the hours left only, 6 hours from 11:00 is 17:00. This is 8 hours behind 09:00 (which is the supposed exam time)  
![](https://imgur.com/iRbI4rM.jpg)

**Comment by seanlowjk** [comment]
Hi Christian!

The issue has been fixed with the latest patch!

Thanks for spotting the issue and Have A Nice Day!
